name = "infrago"
mode = "dev"


[http]
port = 80

[cache]
driver = "redis"

[mutex]
driver = "redis"

[queue]
driver = "redis"
external = true

[data]
driver = "postgres"
url = "postgres://test:test@127.0.0.1:5432/test?sslmode=disable"

[setting]
msg = "hello"
