name = "infrago"
mode = "dev"


[http]
driver = "mux"
port = 80

[cache]
driver = "redis"

[mutex]
driver = "redis"

[queue]
driver = "default"

[event]
driver = "nats"
setting = { "url" = "nats://127.0.0.1:4222", "password" = "password" }

[data]
driver = "postgres"
url = "postgres://test:test@127.0.0.1:5432/test?sslmode=disable"

[setting]
msg = "hello"
